artigos/urls.py
from django.urls import path
from .views import artigos, detalhes

app_name = 'artigos'

urlpatterns = [
    path('', artigos, name='artigos'),
    path('<slug:slug>', detalhes, name='detalhes'),
]

contas/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import registrar

app_name = 'contas'

urlpatterns = [
    path('registrar/', registrar, name='registrar'),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from .views import sobre, home
from artigos import urls as artigos_urls
from contas import urls as contas_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sobre/', sobre),
    path('artigos/', include(artigos_urls)),
    path('contas/', include(contas_urls)),
    path('', home),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artigos/models.py
from django.db import models

class Artigo(models.Model):
    titulo = models.CharField(max_length=100)
    slug = models.SlugField()
    corpo = models.TextField()
    data = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.titulo

    def snippet(self):
        return self.corpo[:50] + '...'

contas/models.py
from django.db import models

# Create your models here.

artigos/views.py
from django.shortcuts import render
from .models import Artigo
from django.http import HttpResponse

def artigos(request):
    artigos = Artigo.objects.all().order_by('data')
    return render(request, "artigos.html",  {'artigos' : artigos})

def detalhes(request, slug):
    artigo = Artigo.objects.get(slug=slug)
    return render(request, 'detalhes.html', {'artigo' : artigo})
    #return HttpResponse(slug)

contas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

def registrar(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("artigos:artigos")
    else:
        form = UserCreationForm()
    return render(request, "registrar.html", {'form' : form})

def login(request):
    return render(request, "login.html")

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, "home.html")
    # return HttpResponse("Home")

def sobre(request):
    return render(request, "sobre.html")
    # return HttpResponse("Sobre")

artigos/templates/artigos.html
{% extends 'base.html' %}

{% block titulo %}Artigos{% endblock %}

{% block conteudo %}
    <h1>Artigos</h1>
    <div class="artigos">
    {% for artigo in artigos %}
        <div class="artigo">
            <h2>
                <a href="{% url 'artigos:detalhes' slug=artigo.slug %}">{{ artigo.titulo }}</a>
            </h2>
            <p>{{ artigo.snippet }}</p>
            <p>{{ artigo.data }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

artigos/templates/detalhes.html
{% extends 'base.html' %}

{% block titulo %}Detalhes{% endblock %}

{% block conteudo %}
    <div class="artigo-detalhe">
        <div class="artigo">
            <img src="{{ artigo.thumb.url }}" alt="{{ artigo.thumb }}">
            <h2>{{ artigo.titulo }}</h2>
            <p>{{ artigo.corpo }}</p>
            <p>{{ artigo.data }}</p>
        </div>
    </div>
{% endblock %}

contas/templates/login.html
{% extends 'base.html' %}

{% block conteudo %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

contas/templates/registrar.html
{% extends 'base.html' %}

{% block conteudo %}
    <h1>Registrar</h1>
    <form class="site-form" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Registrar</button>>
    </form>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block titulo %}{% endblock %}</title>
</head>
<body>

    <header class="wrapper">
        <h1>
            <a href="{% url 'artigos:artigos' %}">
                Listar todos os artigos
            </a>
        </h1>

        {% if user.is_authenticated %}
            Olá {{ user.username }}!
            <p><a href="#">Logout</a></p>
        {% else %}
            <p>Você não está logado</p><a href="#">Login</a>
        {% endif %}
    </header>

    <div class="wrapper">
        {% block conteudo %}
        {% endblock %}
    </div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block titulo %}Home{% endblock %}

{% block conteudo %}
    Home
{% endblock %}

templates/sobre.html
{% extends 'base.html' %}

{% block titulo %}Sobre{% endblock %}

{% block conteudo %}
    Sobre
{% endblock %}